### ISSUE TITLE
Are KEY_SKIP_REWIND and KEY_SKIP_FAST_FORWARD keys defined in Linux?

### ISSUE THREAD

**Issue by daehyunpark** [device-automation-bus/dab-specification-2.0#10]
Is it necessary to support all keys defined in DAB?
In particular, I'm not sure how to define the KEY_SKIP_REWIND and KEY_SKIP_FAST_FORWARD keys on a linux-based platform.

I would appreciate it if you could find a key like this in the linux key codes below.
https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h

**Comment by GaganBhat** [comment]
Good question @daehyunpark -- I think we should flip the question around: 

If there exists a button on the physical user remote that can be mapped to a DAB key as defined, it should be supported.

If there's a DAB key in the spec but it doesn't make sense in the context of platform / remote, it is okay to be omitted. In this case, it's likely your remote has a `KEY_REWIND` and not a `KEY_SKIP_REWIND`, which may be used through `input/long-key-press`.

Please ensure that `input/key/list` is accurately reflecting which keys your implementation supports. Certification tests will query this information before calling `input/key-press` and `input/long-key-press`.

**Comment by daehyunpark** [comment]
I agree. 
I looked for similar functionality to support DAB as much as possible.
I confirmed that input/key/list is queried when testing a key that is not supported.
It will automatically fail after this. We will judge this to be normal operation.
