### ISSUE TITLE
Scope of expansion for supported Voice System

### ISSUE THREAD

**Issue by arun-madhavan-013** [device-automation-bus/dab-specification-2.0#14]
How can device report if it has a non listed voice service support than this table listed ones?
https://github.com/device-automation-bus/dab-specification-2.0/blob/main/DAB.md#voice-system-name-registry

**Comment by GaganBhat** [comment]
If it's not defined within the registry, the implementation may fallback to a default system name. DAB users will query and use the voice service on-demand.

It is highly recommended that you engage with the voice system owner, and get them to add a common friendly name to the registry.
