### ISSUE TITLE
what is the expected response when device is not supported queried feature.

### ISSUE THREAD

**Issue by kvfasil** [device-automation-bus/dab-specification-2.0#17]
Hi team,
what is the expected response, when the device is not supported queried feature.

eg : 
when we query get " SystemSettingsGetConformance "  . but my device is not supported pictureMode.
what is the expected response here.

currently dab looking for a type from below enum, and my device is supported none of them.
```
pub enum PictureMode {
    #[default]
    Standard,
    Dynamic,
    Movie,
    Sports,
    FilmMaker,
    Game,
    Auto,
}
```

```
interface GetCurrentSystemSettingsResponse extends DabResponse {
   language: rfc_5646_language_tag;
   outputResolution: OutputResolution;
   memc: boolean;
   cec: boolean;
   lowLatencyMode: boolean;
   matchContentFrameRate: MatchContentFrameRate;
   hdrOutputMode: HdrOutputMode;
   pictureMode: PictureMode;
   audioOutputMode: AudioOutputMode;
   audioOutputSource: AudioOutputSource;
   videoInputSource: VideoInputSource;
   audioVolume: int;
   mute: boolean;
   textToSpeech: boolean;
}
```

**Comment by GaganBhat** [comment]
If the specific operation is not supported, as per the [Common Response Payload](https://github.com/device-automation-bus/dab-specification-2.0/blob/main/DAB.md#common-dab-response-payload) section, you may return error code 501 with the reason `Not implemented.`.
