### ISSUE TITLE
Unclear to the consumer when the voice request is completed from device

### ISSUE THREAD

**Issue by arun-madhavan-013** [device-automation-bus/dab-specification-2.0#18]
https://github.com/device-automation-bus/dab-specification-2.0?tab=readme-ov-file#59-voice does not specify anything related to when that voice request will be finished from device.

**Real Usecase:**
DAB based test suite might be sending voice related tests back to back. Device might be waiting for first request to complete from VoiceSystem(Eg: Google/Alexa). There is no way that the test suite or requestee knows about the status of first request.

One request completion is dependent on downloading the voice input file, send the input(voice audio file/text input) to voiceSystem, how long the voice system takes to process it, get the response back to device, Device's system UI to handle the voiceSystem's response.

Should DAB response be sent when the voice related operation is completed ?
How long the test suite or requestee need to wait before placing the next request ?

**Comment by arun-madhavan-013** [comment]
Hello @GaganBhat ,
Could you please suggest what is the expected behavior ?

**Comment by GaganBhat** [comment]
@arun-madhavan-013 -- The DAB response should be sent once the voice operation is completed. We have not defined specific timeout or latency periods however.
 
The test suite should wait until a response (failure or pass), and only then continue before placing the next request. Is this not the case today?

**Comment by arun-madhavan-013** [comment]
No; just to clarify, the DAB Voice input(audio/text) API response is sent out as soon as the voice input is given to NLP or VoiceSDK.
It is not waiting till response of NLP which can be more than 2 seconds dependeing on the input query.

Expectation is clear from DAB perpective; we need to wait till NLP response completes.

Thank you for clarifying.
