### ISSUE TITLE
Specification mismatch on List of system settings api .

### ISSUE THREAD

**Issue by kvfasil** [device-automation-bus/dab-specification-2.0#7]
Hi team,
found a mismatch in specification and responses provided by the doc for List of system settings.

https://github.com/device-automation-bus/dab-specification-2.0/blob/845966f6877e1a964575a60e1bafd7d90e634560/DAB.md?plain=1#L858

```
   "audioOutputSource": ["HDMI", "Optical"],
   "videoInputSource": [],
   "audioVolume": false,
   "mute": false,
   "textToSpeech": true
```
   
   
"audioVolume" should have object of audioVolume contain min and max values.
```
      audioVolume: {
      min: int;
      max: int;
   },
```
is it what expected?

**Comment by GaganBhat** [comment]
Hi @kvfasil, nice catch! This is not expected.

We will be updating the sample response specification along with other audio volume control-related clarifications shortly.

**Comment by kvfasil** [comment]
thank you.
